### ISSUE TITLE
Problem while using the code.

### ISSUE THREAD

**Issue by yellowbeango** [13952522076/Efficient_ImageNet_Classification#2]
When I try to deploy the code on GCP using 4 V100 GPUs, the code can not work and throw the following error:
Traceback (most recent call last):
  File "main_cosine.py", line 586, in <module>
    main()
  File "main_cosine.py", line 235, in main
    model = DDP(model, delay_allreduce=True)
  File "/opt/anaconda3/lib/python3.7/site-packages/apex/parallel/distributed.py", line 253, in __init__
    flat_dist_call([param.data for param in self.module.parameters()], dist.broadcast, (0,) )
  File "/opt/anaconda3/lib/python3.7/site-packages/apex/parallel/distributed.py", line 75, in flat_dist_call
    apply_flat_dist_call(bucket, call, extra_args)
  File "/opt/anaconda3/lib/python3.7/site-packages/apex/parallel/distributed.py", line 41, in apply_flat_dist_call
    call(coalesced, *extra_args)
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 810, in broadcast
    work = _default_pg.broadcast([tensor], opts)
RuntimeError: Broken pipe

Python 3.7.4
CUDA Version 10.0.130
CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)
Torch Version 1.3.0

**Comment by ma-xu** [comment]
Please increase the instance CPU memory. Refer https://github.com/open-mmlab/mmdetection/issues/1172#issue-479633549
